# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.4
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- xcodebuild -project '_Pods.xcodeproj' -enableCodeCoverage YES -workspace Example/CircularSlider.xcworkspace -scheme CircularSlider-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6' build test | xcpretty -c --test --color
- pod lib lint
